##############################################################################
# About tasks:
# "Wait 300 seconds, but only start checking after 60 seconds" - try to make ssh connection every 60 seconds until 300 seconds
# "Configure general settings for the KeyOS hosts group" - make provisioning into google cloud KeyOS node
# You have to add all necessary cammans of KeyOS under the block "lines:"
##############################################################################


- name: integration of terraform and ansible
  hosts: all
  gather_facts: 'no'

  tasks:

    - name: "Wait 300 seconds, but only start checking after 60 seconds"
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: "Configure general settings for the KeyOS hosts group"
      keyos_config:
        lines:
          - set system name-server xxx.xxx.xxx.xxx
        save:
          true
