- name: integration of terraform and ansible
  hosts: all
  gather_facts: 'no'

  tasks:

    - name: "Wait 300 seconds, but only start checking after 60 seconds"
      wait_for_connection:
        delay: 5
        timeout: 30

    - name: "Configure general settings for the keyos hosts group"
      keyos_config:
        lines:
          - set system name-server 8.8.8.8
        save:
          true
